{% set name = "imagecodecs" %}
{% set version = "2020.2.18" %}
{% set sha256 = "c019b19438dff31365fee3002b438992c16bc9955a036f466c600d80699cb5a2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<36]
  entry_points:
    - imagecodecs=imagecodecs.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.16.6

test:
  imports:
    - imagecodecs
  commands:
    - imagecodecs --help

about:
  home: "https://www.lfd.uci.edu/~gohlke/"
  license: BSD
  license_family: BSD
  license_file: LICENSE 
  summary: "Image transformation, compression, and decompression codecs"
